/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculator.h"

int *
add_1_svc(Argument *argp, struct svc_req *rqstp)
{
	static int result;

	result = argp->a + argp->b;
	printf("%d + %d = %d\n", argp->a, argp->b, result);

	return &result;
}

int *
subtract_1_svc(Argument *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->a - argp->b;
	printf("%d - %d = %d\n", argp->a, argp->b, result);

	return &result;
}

int *
multiply_1_svc(Argument *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->a * argp->b;
	printf("%d * %d = %d\n", argp->a, argp->b, result);

	return &result;
}

int *
divide_1_svc(Argument *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->a / argp->b;
	printf("%d / %d = %d\n", argp->a, argp->b, result);

	return &result;
}
