version: "3.8"
services:
  base: &base
    build:
      context: .
    working_dir: /app
    tty: true
  server:
    <<: *base
    volumes:
      - ./TransportLayer/server:/app/server
      - ./TransportLayer/services:/app/services
  client: &client
    <<: *base
    volumes:
      - ./TransportLayer/client:/app/client
      - ./TransportLayer/services:/app/services

  client2: *client
